package main

import (
	"testing"

	"github.com/google/go-cmp/cmp"
)

var testPolicyNoTrace = []string{
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*mangle",
	":PREROUTING ACCEPT [6644470:1039872350]",
	":INPUT ACCEPT [6644470:1039872350]",
	":FORWARD ACCEPT [0:0]",
	":OUTPUT ACCEPT [6093378:960619800]",
	":POSTROUTING ACCEPT [6093378:960619800]",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*raw",
	":PREROUTING ACCEPT [2502678:375978678]",
	":OUTPUT ACCEPT [2325323:325134634]",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*filter",
	":INPUT ACCEPT [38659:3282330]",
	":FORWARD ACCEPT [0:0]",
	":OUTPUT ACCEPT [35452:1942057]",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*nat",
	":PREROUTING ACCEPT [1292886:69592056]",
	":POSTROUTING ACCEPT [71297:4698134]",
	":OUTPUT ACCEPT [71295:4698054]",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
}

var testPolicyNoTraceRules = []string{
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*mangle",
	":PREROUTING ACCEPT [6644470:1039872350]",
	":INPUT ACCEPT [6644470:1039872350]",
	":FORWARD ACCEPT [0:0]",
	":OUTPUT ACCEPT [6093378:960619800]",
	":POSTROUTING ACCEPT [6093378:960619800]",
	"-A INPUT -j ACCEPT",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*raw",
	":PREROUTING ACCEPT [2502678:375978678]",
	":OUTPUT ACCEPT [2325323:325134634]",
	"-A OUTPUT -j ACCEPT",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*filter",
	":INPUT ACCEPT [38659:3282330]",
	":FORWARD ACCEPT [0:0]",
	":OUTPUT ACCEPT [35452:1942057]",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*nat",
	":PREROUTING ACCEPT [1292886:69592056]",
	":POSTROUTING ACCEPT [71297:4698134]",
	":OUTPUT ACCEPT [71295:4698054]",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
}

var testPolicyTraceID3 = []string{
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*mangle",
	":PREROUTING ACCEPT [6644470:1039872350]",
	":INPUT ACCEPT [6644470:1039872350]",
	":FORWARD ACCEPT [0:0]",
	":OUTPUT ACCEPT [6093378:960619800]",
	":POSTROUTING ACCEPT [6093378:960619800]",
	"-I PREROUTING -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:0\" --nflog-group 22",
	"-I INPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:1\" --nflog-group 22",
	"-I FORWARD -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:2\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:3\" --nflog-group 22",
	"-I POSTROUTING -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:4\" --nflog-group 22",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*raw",
	":PREROUTING ACCEPT [2502678:375978678]",
	":OUTPUT ACCEPT [2325323:325134634]",
	"-I PREROUTING -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:5\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:6\" --nflog-group 22",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*filter",
	":INPUT ACCEPT [38659:3282330]",
	":FORWARD ACCEPT [0:0]",
	":OUTPUT ACCEPT [35452:1942057]",
	"-I INPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:7\" --nflog-group 22",
	"-I FORWARD -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:8\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:9\" --nflog-group 22",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*nat",
	":PREROUTING ACCEPT [1292886:69592056]",
	":POSTROUTING ACCEPT [71297:4698134]",
	":OUTPUT ACCEPT [71295:4698054]",
	"-I PREROUTING -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:10\" --nflog-group 22",
	"-I POSTROUTING -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:11\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:12\" --nflog-group 22",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
}

var testPolicyTraceID3and4 = []string{
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*mangle",
	":PREROUTING ACCEPT [6644470:1039872350]",
	":INPUT ACCEPT [6644470:1039872350]",
	":FORWARD ACCEPT [0:0]",
	":OUTPUT ACCEPT [6093378:960619800]",
	":POSTROUTING ACCEPT [6093378:960619800]",
	"-I PREROUTING -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:0\" --nflog-group 22",
	"-I INPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:1\" --nflog-group 22",
	"-I FORWARD -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:2\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:3\" --nflog-group 22",
	"-I POSTROUTING -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:4\" --nflog-group 22",
	"-I PREROUTING -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:4:0\" --nflog-group 22",
	"-I INPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:4:1\" --nflog-group 22",
	"-I FORWARD -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:4:2\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:4:3\" --nflog-group 22",
	"-I POSTROUTING -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:4:4\" --nflog-group 22",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*raw",
	":PREROUTING ACCEPT [2502678:375978678]",
	":OUTPUT ACCEPT [2325323:325134634]",
	"-I PREROUTING -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:5\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:6\" --nflog-group 22",
	"-I PREROUTING -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:4:5\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:4:6\" --nflog-group 22",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*filter",
	":INPUT ACCEPT [38659:3282330]",
	":FORWARD ACCEPT [0:0]",
	":OUTPUT ACCEPT [35452:1942057]",
	"-I INPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:7\" --nflog-group 22",
	"-I FORWARD -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:8\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:9\" --nflog-group 22",
	"-I INPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:4:7\" --nflog-group 22",
	"-I FORWARD -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:4:8\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:4:9\" --nflog-group 22",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*nat",
	":PREROUTING ACCEPT [1292886:69592056]",
	":POSTROUTING ACCEPT [71297:4698134]",
	":OUTPUT ACCEPT [71295:4698054]",
	"-I PREROUTING -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:10\" --nflog-group 22",
	"-I POSTROUTING -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:11\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:3:12\" --nflog-group 22",
	"-I PREROUTING -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:4:10\" --nflog-group 22",
	"-I POSTROUTING -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:4:11\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -j NFLOG --nflog-prefix \"iptr:4:12\" --nflog-group 22",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
}

var testPolicyTraceID5withMark = []string{
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*mangle",
	":PREROUTING ACCEPT [6644470:1039872350]",
	":INPUT ACCEPT [6644470:1039872350]",
	":FORWARD ACCEPT [0:0]",
	":OUTPUT ACCEPT [6093378:960619800]",
	":POSTROUTING ACCEPT [6093378:960619800]",
	"-I PREROUTING -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:5:0\" --nflog-group 22",
	"-I INPUT -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:5:1\" --nflog-group 22",
	"-I FORWARD -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:5:2\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:5:3\" --nflog-group 22",
	"-I POSTROUTING -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:5:4\" --nflog-group 22",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*raw",
	":PREROUTING ACCEPT [2502678:375978678]",
	":OUTPUT ACCEPT [2325323:325134634]",
	"-I PREROUTING -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:5:5\" --nflog-group 22",
	"-I PREROUTING -s 1.2.3.4 -m comment --comment \"iptr:5:mark\" -m limit --limit 60/minute --limit-burst 1 -j MARK --set-xmark 0x124/0x124",
	"-I OUTPUT -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:5:6\" --nflog-group 22",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*filter",
	":INPUT ACCEPT [38659:3282330]",
	":FORWARD ACCEPT [0:0]",
	":OUTPUT ACCEPT [35452:1942057]",
	"-I INPUT -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:5:7\" --nflog-group 22",
	"-I FORWARD -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:5:8\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:5:9\" --nflog-group 22",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*nat",
	":PREROUTING ACCEPT [1292886:69592056]",
	":POSTROUTING ACCEPT [71297:4698134]",
	":OUTPUT ACCEPT [71295:4698054]",
	"-I PREROUTING -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:5:10\" --nflog-group 22",
	"-I POSTROUTING -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:5:11\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:5:12\" --nflog-group 22",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
}

var testPolicyTraceID6withMarkAndRules = []string{
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*mangle",
	":PREROUTING ACCEPT [6644470:1039872350]",
	":INPUT ACCEPT [6644470:1039872350]",
	":FORWARD ACCEPT [0:0]",
	":OUTPUT ACCEPT [6093378:960619800]",
	":POSTROUTING ACCEPT [6093378:960619800]",
	"-A INPUT -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:6:0\" --nflog-group 22",
	"-A INPUT -j ACCEPT",
	"-I PREROUTING -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:6:1\" --nflog-group 22",
	"-I INPUT -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:6:2\" --nflog-group 22",
	"-I FORWARD -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:6:3\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:6:4\" --nflog-group 22",
	"-I POSTROUTING -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:6:5\" --nflog-group 22",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*raw",
	":PREROUTING ACCEPT [2502678:375978678]",
	":OUTPUT ACCEPT [2325323:325134634]",
	"-A OUTPUT -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:6:6\" --nflog-group 22",
	"-A OUTPUT -j ACCEPT",
	"-I PREROUTING -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:6:7\" --nflog-group 22",
	"-I PREROUTING -s 1.2.3.4 -m comment --comment \"iptr:6:mark\" -m limit --limit 60/minute --limit-burst 1 -j MARK --set-xmark 0x124/0x124",
	"-I OUTPUT -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:6:8\" --nflog-group 22",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*filter",
	":INPUT ACCEPT [38659:3282330]",
	":FORWARD ACCEPT [0:0]",
	":OUTPUT ACCEPT [35452:1942057]",
	"-I INPUT -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:6:9\" --nflog-group 22",
	"-I FORWARD -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:6:10\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:6:11\" --nflog-group 22",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
	"# Generated by iptables-save v1.6.0 on Sat Nov 24 11:59:50 2018",
	"*nat",
	":PREROUTING ACCEPT [1292886:69592056]",
	":POSTROUTING ACCEPT [71297:4698134]",
	":OUTPUT ACCEPT [71295:4698054]",
	"-I PREROUTING -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:6:12\" --nflog-group 22",
	"-I POSTROUTING -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:6:13\" --nflog-group 22",
	"-I OUTPUT -s 1.2.3.4 -m mark --mark 0x124/0x124 -j NFLOG --nflog-prefix \"iptr:6:14\" --nflog-group 22",
	"COMMIT",
	"# Completed on Sat Nov 24 11:59:50 2018",
}

func TestClearIptablesPolicy(t *testing.T) {
	policies := []struct {
		policy    []string
		cleanupID int
		expected  []string
	}{
		{nil, 0, nil},
		{[]string{"foobar"}, 0, []string{"foobar"}},
		{testPolicyNoTrace, 0, testPolicyNoTrace},
		{testPolicyNoTraceRules, 0, testPolicyNoTraceRules},
		{testPolicyNoTrace, 3, testPolicyNoTrace},
		{testPolicyTraceID3, 3, testPolicyNoTrace},
		{testPolicyTraceID3, 0, testPolicyNoTrace},
		{testPolicyTraceID3, 4, testPolicyTraceID3},
		{testPolicyTraceID3and4, 4, testPolicyTraceID3},
		{testPolicyTraceID3and4, 5, testPolicyTraceID3and4},
		{testPolicyTraceID3and4, 0, testPolicyNoTrace},
		{testPolicyTraceID5withMark, 5, testPolicyNoTrace},
		{testPolicyTraceID5withMark, 0, testPolicyNoTrace},
		{testPolicyTraceID5withMark, 6, testPolicyTraceID5withMark},
		{testPolicyTraceID6withMarkAndRules, 6, testPolicyNoTraceRules},
		{testPolicyTraceID6withMarkAndRules, 0, testPolicyNoTraceRules},
		{testPolicyTraceID6withMarkAndRules, 7, testPolicyTraceID6withMarkAndRules},
	}

	for _, policy := range policies {
		got := clearIptablesPolicy(policy.policy, policy.cleanupID)
		if !cmp.Equal(got, policy.expected) {
			t.Errorf("clearIptablesPolicy was incorrect, got: '%s', expected: '%s'", got, policy.expected)
		}
	}
}

var testRuleMap = map[int]iptablesRule{
	0:  {Table: "mangle", Chain: "PREROUTING", ChainEntry: true},
	1:  {Table: "mangle", Chain: "INPUT", ChainEntry: true},
	2:  {Table: "mangle", Chain: "FORWARD", ChainEntry: true},
	3:  {Table: "mangle", Chain: "OUTPUT", ChainEntry: true},
	4:  {Table: "mangle", Chain: "POSTROUTING", ChainEntry: true},
	5:  {Table: "raw", Chain: "PREROUTING", ChainEntry: true},
	6:  {Table: "raw", Chain: "OUTPUT", ChainEntry: true},
	7:  {Table: "filter", Chain: "INPUT", ChainEntry: true},
	8:  {Table: "filter", Chain: "FORWARD", ChainEntry: true},
	9:  {Table: "filter", Chain: "OUTPUT", ChainEntry: true},
	10: {Table: "nat", Chain: "PREROUTING", ChainEntry: true},
	11: {Table: "nat", Chain: "POSTROUTING", ChainEntry: true},
	12: {Table: "nat", Chain: "OUTPUT", ChainEntry: true},
}

var testRuleMapWithRules = map[int]iptablesRule{
	0:  {Table: "mangle", Chain: "INPUT", Rule: "-j ACCEPT", ChainEntry: false},
	1:  {Table: "mangle", Chain: "PREROUTING", ChainEntry: true},
	2:  {Table: "mangle", Chain: "INPUT", ChainEntry: true},
	3:  {Table: "mangle", Chain: "FORWARD", ChainEntry: true},
	4:  {Table: "mangle", Chain: "OUTPUT", ChainEntry: true},
	5:  {Table: "mangle", Chain: "POSTROUTING", ChainEntry: true},
	6:  {Table: "raw", Chain: "OUTPUT", Rule: "-j ACCEPT", ChainEntry: false},
	7:  {Table: "raw", Chain: "PREROUTING", ChainEntry: true},
	8:  {Table: "raw", Chain: "OUTPUT", ChainEntry: true},
	9:  {Table: "filter", Chain: "INPUT", ChainEntry: true},
	10: {Table: "filter", Chain: "FORWARD", ChainEntry: true},
	11: {Table: "filter", Chain: "OUTPUT", ChainEntry: true},
	12: {Table: "nat", Chain: "PREROUTING", ChainEntry: true},
	13: {Table: "nat", Chain: "POSTROUTING", ChainEntry: true},
	14: {Table: "nat", Chain: "OUTPUT", ChainEntry: true},
}

func TestExtendIptablesPolicy(t *testing.T) {
	tables := []struct {
		policy            []string
		traceID           int
		traceFilter       string
		fwMark            int
		packetLimit       int
		traceRules        bool
		nflogGroup        int
		expectedPolicy    []string
		expectedRuleMap   map[int]iptablesRule
		expectedMaxLength int
	}{
		{nil, 0, "", 0, 0, false, 22, nil, map[int]iptablesRule{}, 0},
		{testPolicyNoTrace, 3, "-s 1.2.3.4", 0, 0, false, 22, testPolicyTraceID3, testRuleMap, 11},
		{testPolicyTraceID3, 4, "-s 1.2.3.4", 0, 0, false, 22, testPolicyTraceID3and4, testRuleMap, 11},
		{testPolicyNoTrace, 5, "-s 1.2.3.4", 0x124, 60, false, 22, testPolicyTraceID5withMark, testRuleMap, 11},
		{testPolicyNoTraceRules, 6, "-s 1.2.3.4", 0x124, 60, true, 22, testPolicyTraceID6withMarkAndRules, testRuleMapWithRules, 11},
	}

	for _, table := range tables {
		gotPolicy, gotRuleMap, gotMaxLength := extendIptablesPolicy(table.policy, table.traceID, table.traceFilter, table.fwMark, table.packetLimit, table.traceRules, table.nflogGroup)
		if !cmp.Equal(gotPolicy, table.expectedPolicy) {
			t.Errorf("clearIptablesPolicy returned policy was incorrect, got: '%s', expected: '%s'", gotPolicy, table.expectedPolicy)
		}
		if !cmp.Equal(gotRuleMap, table.expectedRuleMap) {
			t.Errorf("clearIptablesPolicy returned rule map was incorrect, got: '%v', expected: '%v'", gotRuleMap, table.expectedRuleMap)
		}
		if gotMaxLength != table.expectedMaxLength {
			t.Errorf("clearIptablesPolicy returned max length was incorrect, got: '%d', expected: '%d'", gotMaxLength, table.expectedMaxLength)
		}
	}
}
